---
  language: go
  sudo: required
  services:
    - docker
  notifications:
    email: anak10thn@gmail.com
  go:
    - 1.6.x
    - 1.7.x
    - master
  install:
    - go get github.com/golang/lint/golint
    - go get github.com/docker/go-plugins-helpers/volume
    - go get github.com/orcinustools/odorous/rest
  script:
    - test -z "$(go vet ./... | tee /dev/stderr)"
    - test -z "$(golint ./... | tee /dev/stderr)"
    - go list ./... | go test -v
    - make push
