FROM golang:1.7-alpine

COPY . /go/src/github.com/orcinustools/odorous
WORKDIR /go/src/github.com/orcinustools/odorous

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
    gcc libc-dev git    
RUN go get github.com/docker/go-plugins-helpers/volume \
	&& go get github.com/orcinustools/odorous/rest
RUN go install --ldflags '-extldflags "-static"'
RUN apk del .build-deps

CMD ["/go/bin/odorous"]